// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace TariffCardService.DataAccess.Migrations
{
	/// <inheritdoc />
    public partial class B3225 : Migration
    {
	    /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
	        migrationBuilder.CreateTable(
                name: "SearchParamsAliases",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Alias = table.Column<string>(type: "text", nullable: true),
                    DisplayName = table.Column<string>(type: "text", nullable: true),
                    RegionGroupId = table.Column<int>(type: "integer", nullable: false),
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SearchParamsAliases", x => x.Id);
                });

	        migrationBuilder.CreateIndex(
                name: "IX_SearchParamsAliases_Alias_DisplayName",
                table: "SearchParamsAliases",
                columns: new[] { "Alias", "DisplayName" });
        }

	    /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "SearchParamsAliases");
        }
    }
}
